# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network.ui'
#
# Created: Wed Mar 25 19:35:13 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide.QtCore import *
from PySide.QtGui import *

class Network(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(314, 468)
        self.lb_interface = QLabel(Dialog)
        self.lb_interface.setGeometry(QRect(10, 10, 111, 20))
        self.lb_interface.setAlignment(Qt.AlignCenter)
        self.lb_interface.setObjectName("lb_interface")
        self.listWidget = QListWidget(Dialog)
        self.listWidget.setGeometry(QRect(10, 30, 111, 61))
        self.listWidget.setObjectName("listWidget")
        self.pb_up = QPushButton(Dialog)
        self.pb_up.setGeometry(QRect(140, 40, 71, 41))
        self.pb_up.setObjectName("pb_up")
        self.pb_down = QPushButton(Dialog)
        self.pb_down.setGeometry(QRect(230, 40, 71, 41))
        self.pb_down.setObjectName("pb_down")
        self.lb_downloadlimit = QLabel(Dialog)
        self.lb_downloadlimit.setGeometry(QRect(20, 130, 101, 16))
        self.lb_downloadlimit.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lb_downloadlimit.setObjectName("lb_downloadlimit")
        self.lb_uploadlimit_2 = QLabel(Dialog)
        self.lb_uploadlimit_2.setGeometry(QRect(20, 100, 101, 16))
        self.lb_uploadlimit_2.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.lb_uploadlimit_2.setObjectName("lb_uploadlimit_2")
        self.lineEdit = QLineEdit(Dialog)
        self.lineEdit.setGeometry(QRect(130, 100, 113, 23))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QRect(130, 130, 113, 23))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lb_kbps = QLabel(Dialog)
        self.lb_kbps.setGeometry(QRect(250, 100, 31, 21))
        self.lb_kbps.setObjectName("lb_kbps")
        self.lb_kbps_2 = QLabel(Dialog)
        self.lb_kbps_2.setGeometry(QRect(250, 130, 31, 21))
        self.lb_kbps_2.setObjectName("lb_kbps_2")
        self.lb_appupdownlimit = QLabel(Dialog)
        self.lb_appupdownlimit.setGeometry(QRect(10, 180, 301, 20))
        self.lb_appupdownlimit.setAlignment(Qt.AlignCenter)
        self.lb_appupdownlimit.setObjectName("lb_appupdownlimit")
        self.listView = QListView(Dialog)
        self.listView.setGeometry(QRect(10, 240, 301, 131))
        self.listView.setObjectName("listView")
        self.pb_add = QPushButton(Dialog)
        self.pb_add.setGeometry(QRect(20, 210, 95, 24))
        self.pb_add.setObjectName("pb_add")
        self.pb_remove = QPushButton(Dialog)
        self.pb_remove.setGeometry(QRect(210, 210, 95, 24))
        self.pb_remove.setObjectName("pb_remove")
        self.lineEdit_3 = QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QRect(40, 370, 61, 23))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QLineEdit(Dialog)
        self.lineEdit_4.setGeometry(QRect(160, 370, 61, 23))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lb_upload = QLabel(Dialog)
        self.lb_upload.setGeometry(QRect(20, 370, 21, 21))
        self.lb_upload.setObjectName("lb_upload")
        self.label = QLabel(Dialog)
        self.label.setGeometry(QRect(120, 370, 41, 21))
        self.label.setObjectName("label")
        self.pushButton = QPushButton(Dialog)
        self.pushButton.setGeometry(QRect(250, 370, 61, 24))
        self.pushButton.setObjectName("pushButton")
        self.pb_close = QPushButton(Dialog)
        self.pb_close.setGeometry(QRect(20, 430, 95, 24))
        self.pb_close.setObjectName("pb_close")
        self.pb_apply = QPushButton(Dialog)
        self.pb_apply.setGeometry(QRect(200, 430, 95, 24))
        self.pb_apply.setObjectName("pb_apply")

        self.retranslateUi(Dialog)
        QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QApplication.translate("Dialog", "Dialog", None, QApplication.UnicodeUTF8))
        self.lb_interface.setText(QApplication.translate("Dialog", "Interfaces", None, QApplication.UnicodeUTF8))
        self.pb_up.setText(QApplication.translate("Dialog", "Up", None, QApplication.UnicodeUTF8))
        self.pb_down.setText(QApplication.translate("Dialog", "Down", None, QApplication.UnicodeUTF8))
        self.lb_downloadlimit.setText(QApplication.translate("Dialog", "Download Limit", None, QApplication.UnicodeUTF8))
        self.lb_uploadlimit_2.setText(QApplication.translate("Dialog", "Upload Limit", None, QApplication.UnicodeUTF8))
        self.lb_kbps.setText(QApplication.translate("Dialog", "kb/s", None, QApplication.UnicodeUTF8))
        self.lb_kbps_2.setText(QApplication.translate("Dialog", "kb/s", None, QApplication.UnicodeUTF8))
        self.lb_appupdownlimit.setText(QApplication.translate("Dialog", "Application Upload/Download Limit", None, QApplication.UnicodeUTF8))
        self.pb_add.setText(QApplication.translate("Dialog", "Add", None, QApplication.UnicodeUTF8))
        self.pb_remove.setText(QApplication.translate("Dialog", "Remove", None, QApplication.UnicodeUTF8))
        self.lb_upload.setText(QApplication.translate("Dialog", "Up", None, QApplication.UnicodeUTF8))
        self.label.setText(QApplication.translate("Dialog", "Down", None, QApplication.UnicodeUTF8))
        self.pushButton.setText(QApplication.translate("Dialog", "Set", None, QApplication.UnicodeUTF8))
        self.pb_close.setText(QApplication.translate("Dialog", "Close", None, QApplication.UnicodeUTF8))
        self.pb_apply.setText(QApplication.translate("Dialog", "Apply", None, QApplication.UnicodeUTF8))

